name: CI/CD (Clean up)

on:
  pull_request:
    types: [closed]
  workflow_dispatch: ~

env:
  SOURCE_BRANCH: ${{ github.head_ref || github.ref_name }}
  RELEASE_BRANCH: "release/${{ github.head_ref || github.ref_name }}"

jobs:
  clean-up:
    name: Clean up
    runs-on: [ubuntu-latest]
    permissions:
      contents: write
    steps:
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "heads/${{ env.RELEASE_BRANCH }}",
            });
