name: CI/CD (Clean up)

on:
  pull_request:
    types: [closed]
  workflow_dispatch: ~

env:
  SOURCE_BRANCH: ${{ github.head_ref || github.ref_name }}
  RELEASE_BRANCH: "release/${{ github.head_ref || github.ref_name }}"

jobs:
  clean-up:
    name: Clean up
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: |
            github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "heads/${{ env.RELEASE_BRANCH }}",
            });
